config/routes.rb
Nicely::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match 'intro' => 'intro#onboard'
  match 'browse' => 'pages#browse'
  match 'search' => 'pages#search'

  resources :users do
    member do
      post 'give_feedback'
    end
    resources :feedback
    resources :notifications
  end

  resources :tasks do
    resources :messages
    resources :reports
    resources :offers do
      post 'revoke'
      get  'accept'
    end
    member do
      post 'delete'
      post 'like'
      post 'unlike'
      post 'revoke'
      get 'complete'
      get 'chat'
    end
  end

  resources :comments

  root to: 'pages#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  TASK_PER_PAGE = 10
  ACTIVE_TASK = 0

  include Tire::Model::Search
  include Tire::Model::Callbacks
  self.table_name = 'tasks'
  self.rgeo_factory_generator = RGeo::Geos.factory_generator(srid: 4326)
  RGeo::ActiveRecord::GeometryMixin.set_json_generator(:geojson)
  set_rgeo_factory_for_column(:start_xy,
                              self.rgeo_factory_generator)
  set_rgeo_factory_for_column(:end_xy,
                              self.rgeo_factory_generator)
  attr_accessible :description, :status, :title,
                  :start_time, :start_loc, :end_loc,
                  :estimated_time, :start_xy, :end_xy,
                  :points
  validates_presence_of :description, :title, :estimated_time, :start_loc
  before_save :default_values
  belongs_to :user
  has_one :assignee, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :reports, dependent: :destroy

  scope :close_to, ->(latitude, longitude, distance_in_meters = 10000) {
    where(%{
      ST_DWithin(
        tasks.start_xy,
        ST_GeographyFromText('SRID=4326;POINT(%f %f)'),
        %d
      )
      } % [longitude, latitude, distance_in_meters]
    )
  }

  scope :active, -> {
    where(%{
        tasks.status = 0
      }
    )
  }

  after_save do
    if deleted_at.nil?
      self.index.store self
    else
      self.index.remove self
    end
  end


  def default_values
    self.status ||= 0
    self.points ||= 1
    self.start_loc ||= 'None'
    self.end_loc ||= 'None'
  end

  def is_owner?(user)
    self.user.id == user.id
  end

  def active?
    self.status == ACTIVE_TASK
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, only: [:like, :new, :edit, :update, :destroy, :complete, :chat]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html { render layout: 'application', template: 'tasks/new' }
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html {render layout: 'application', template: 'tasks/show' }  # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @back_path = request.referer || root_path
    respond_to do |format|
      format.html {
        render layout: 'application', template: 'tasks/new'
      }
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    redirect_to task_path(@task) and return
  end

  def delete
    @task = Task.find_by_id(params[:id])
    @task.destroy
    if @task.destroyed?
      render json: { success: true } and return
    else
      render json: { success: false } and return
    end
  end

  def like
    @task = Task.find_by_id(params[:id])
    @user = User.find_by_id(params[:user_id])
    @user.like(@task)
    if @user.likes?(@task)
      render json: { success: true } and return
    else
      render json: { success: false } and return
    end
  end

  def unlike
    @task = Task.find_by_id(params[:id])
    @user = User.find_by_id(params[:user_id])
    @user.unlike(@task)
    if !@user.likes?(@task)
      render json: { success: true } and return
    else
      render json: { success: false } and return
    end
  end

  def revoke
    @task = Task.find_by_id(params[:id])
    if @task.assignee
      @task.assignee = nil
      if @task.save
        render json: { success: true } and return
      end
    end
    render json: { success: false } and return
  end

  def complete
    @task = Task.find(params[:id])
    task_completer = @task.assignee.user
    task_completer.points += @task.liked_by_count + @task.points
    @task.status = 1
    if @task.save && task_completer.save
      puts task_completer.points
      render 'tasks/complete' and return
    else
      flash[:notice] =  {type: "failure", message: "Task not completed"}
      redirect_to task_path(@task) unless @task.is_owner?(current_user)
    end
  end

  def chat
    @task = Task.find(params[:id])
    unless @task.user.id == current_user.id ||
        (@task.assignee && @task.assignee.user.id == current_user.id)
      redirect_to task_path(@task) and return
    end

    @message = Message.new
    render 'tasks/chat' and return
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = User.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:user])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    #@task.destroy

    respond_to do |format|
      format.html { redirect_to task_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/task_helper.rb
module TaskHelper
  def has_user_offer?
    current_user && !@task.offers.where(user_id: current_user.id).empty?
  end

  def has_user_report?
    current_user && !@task.reports.where(user_id: current_user.id).empty?
  end
end

app/views/tasks/_feed_summary.haml
.feed-summary
  .title
    .liked
      .icon{class: liked(feed_summary), data: {task_id: feed_summary.id} }
      .count
        %p{data: {count: feed_summary.liked_by_count + feed_summary.offers.count} }
          = feed_summary.liked_by_count + feed_summary.offers.count
    .text
      %h2
        = link_to strip_tags(feed_summary.title), task_path(feed_summary)
      %h1
        = task_distance(feed_summary)
        miles away
  .details
    .avatar
      = link_to image_tag(gravatar_url(feed_summary.user.email, gravatar_size)), user_path(feed_summary.user)
    .submission
      .submitter
        %span
          Submitted by
          = link_to feed_summary.user.display_name, user_path(feed_summary.user)
        %p.ago
          Created
          = distance_of_time_in_words_to_now(feed_summary.created_at)
          ago

app/views/tasks/_interact.haml
.interact
  %ul
    - if (user_signed_in? && current_user.id == task.user.id)
      %li
        - if task.assignee
          = link_to 'Get Different Help', '#help', class: 'button active', id: 'revoke-button'
        - else
          = link_to 'View Offers', task_offers_path(task), class: 'button active'
      - if task.assignee
        %li
          =  link_to 'Task Completed', complete_task_path(task), class: 'button active', id: 'complete-button'

      - if !task.assignee
        %li
          = link_to 'Delete', '#delete', class: 'button active report', id: 'delete-button'
    - else
      %li
        - if has_user_offer?
          = link_to 'Help Offered', '#help', class: 'button disabled', id: 'help-button'
        - else
          = link_to 'Offer Help', '#help', class: 'button active', id: 'help-button'
      %li
        - if has_user_report?
          = link_to 'Reported', '#report', class: 'button disabled', id: 'report-button'
        - else
          = link_to 'Report', '#report', class: 'button active report', id: 'report-button'
    - if user_signed_in? && task.assignee && (current_user.id == task.user.id || current_user.id == task.assignee.user.id)
      = link_to 'Chat', chat_task_path(task), class: 'button active', id: 'chat-button'

app/views/tasks/_message.haml
%li
  %h1
    = message.sender.display_name
    %span.grey
      said
      = distance_of_time_in_words_to_now(message.created_at)
      ago

  %p
    = message.content

app/views/tasks/_summary.haml
.summary
  %p
    = link_to strip_tags(summary.title), task_path(summary)
  .details
    .avatar
      = link_to image_tag(gravatar_url(summary.user.email, gravatar_size)), user_path(summary.user)
    .submission
      .submitter
        %span
          Submitted by
          = link_to summary.user.display_name, user_path(summary.user)
        %p.ago
          Created
          = distance_of_time_in_words_to_now(summary.created_at)
          ago

app/views/tasks/chat.haml
= subscribe_to chat_task_path(@task)
%script#message-template{type: 'text/template'}
  %li
    %h1
      {{ name }}
      %span.grey
        said
        {{ time_ago }}
        ago

    %p
      {{ content }}
.chat
  .form
    %ul.messages
      - if @task.messages
        = render partial: 'tasks/message', collection: @task.messages
    = form_for [@task, @message], remote: true do |f|
      %div.controls
        = f.text_area :content, class: 'text'
        = f.submit "Submit", class: 'button signup-button'
      %div
        = f.hidden_field :sender_id, value: current_user.id

= content_for :javascript do
  = javascript_include_tag 'nicely/tasks/TaskChatView.js'

= content_for :javascript do
  :javascript
    jQuery(document).ready(function($){
      var taskChatView = new Nicely.Tasks.TaskChatView("#{chat_task_path(@task)}", {el: '.chat'});
    });

app/views/tasks/complete.haml
.feedback
  %h3 Awesome! Use the form below to add feedback about your helper.
  .form
    = form_for Comment.new, url: give_feedback_user_path(@task.assignee.user) do |f|
      %div
        = f.text_area :text
      %div
        = f.hidden_field :commenter_id, value: @task.user.id
      %div= f.submit "Submit", class: 'button signup-button'
      %div.nope
        = link_to 'No thanks', root_path, class: 'button signup-button no-padding'

app/views/tasks/new.haml
.form
  .page-form
    .form-contents
      .text
        %h3 Ask for a kind favor
        = form_for(@task, :url => tasks_path) do |f|
          - if @task.errors.any?
            #error_explanation
              %h2
                = pluralize(@task.errors.count, 'error')
                kept this task from being saved
              %ul
                - @task.errors.full_messages.each do |message|
                  %li
                    = message
          %div
            = f.label :title
            %br/
            = f.text_field :title, autofocus: true, maxlength: 244
          %div
            = f.label :description
            %br/
            = f.text_area :description, maxlength: 244
          %div
            = f.label :start_loc, 'Start Location'
            %br/
            = f.text_field :start_loc
          %div
            = f.label :start_time, 'I need task completed by:'
            %br/
            = f.datetime_select :start_time, ampm: true
          %div
            = f.label :end_loc, 'End Location (Optional)'
            %br/
            = f.text_field :end_loc
          %div
            = f.label :estimated_time, 'Estimated Time'
            %br/
            .inline
              = f.number_field :estimated_time
            %p.inline-label minutes
          %div
            = f.hidden_field :start_xy
            = f.hidden_field :end_xy

          %div= f.submit "Submit", class: 'button signup-button'
          %div= link_to 'Cancel', root_path, class: 'button report signup-button no-padding', id: 'cancel-button'
      #map_container
        %h3.before-location Enter a Start or End location
        #map_canvas

= content_for :javascript do
  = javascript_include_tag 'nicely/tasks/manifest.js'
  :javascript
    jQuery(document).ready(function($){
      var taskForm = new Nicely.Tasks.TaskForm({el: '.page-form'});
    });

app/views/tasks/show.haml
.task
  .map
    #map-canvas
  .task-content
    - if flash[:notice]
      = render partial: 'pages/notice'
    .left
      .title
        %h3.medium-padding
          = truncate(strip_tags(@task.title), length: 80)
      .details
        %p.ago.h2
          Submitted
          = time_ago_in_words(@task.created_at, Time.now)
          ago by
          = link_to @task.user.display_name, user_path(@task.user)
        .liked
          .icon{class: liked(@task), data: {task_id: @task.id} }
          .count
            %p{data: {count: @task.liked_by_count + @task.offers.count} }
              = @task.liked_by_count + @task.offers.count
        .location
          %ul
            %li
              %span.field.h2
                Start Location:
              %span.data.h2
                = @task.start_loc
            %li
              %span.field.h2
                Task starts in:
              %span.data.h2
                = distance_of_time_in_words_to_now(@task.start_time)
            %li
              %span.field.h2
                End Location:
              %span.data.h2
                = @task.end_loc

            %li
              %span.field.h2
                Estimated Time:
              %span.data.h2
                = "#{@task.estimated_time} minutes"

        %p.description{data: {p: @task.description }}
          = strip_tags(@task.description)
        - if @task.active? && user_signed_in?
          = render partial: 'tasks/interact', locals: {task: @task}
      .comments
    .right
      .status
        - if @task.assignee && @task.active?
          %h3.medium-padding.in-progress
            Task in progress
        - elsif !@task.active?
          %h3.medium-padding
            Task completed
        - else
          %h3.medium-padding
            Nice people needed
        %p.grey.h2
          There are
          = link_to "#{@task.offers.count}", task_offers_url(@task), class: 'normal-link', id: 'offers'
          offers
        .share
          %h3.medium-padding
            Share to:
          %ul
            %li
              = link_to 'Share to Facebook', "https://www.facebook.com/sharer/sharer.php?u=#{CGI.escape(request.original_url)}",
                class: 'facebook-icon', id: 'share-facebook'
            %li
              = link_to 'Share to Twitter', "https://twitter.com/intent/tweet?url=#{CGI.escape(request.original_url)}", class: 'twitter-icon', id: 'share-twitter'
            %li
              %script{type: 'text/javascript', src: 'http://www.reddit.com/static/button/button3.js'}

= content_for :javascript do
  = javascript_include_tag 'nicely/tasks/manifest.js'
= content_for :javascript do
  :javascript
    jQuery(document).ready(function($){
      tasksController = new Nicely.Tasks.TasksController();
      tasksController
        .newOfferURL("#{task_offers_url(@task)}")
        .newReportURL("#{task_reports_url(@task)}")
      var taskView = new Nicely.Tasks.TaskView(tasksController, #{@task.to_json}, "#{root_path}", { el: '.task'});
    });
  - if user_signed_in?
    :javascript
      jQuery(document).ready(function($){
        tasksController.userID(#{current_user.id});
      });