config/routes.rb
Nicely::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match 'intro' => 'intro#onboard'
  match 'browse' => 'pages#browse'
  match 'search' => 'pages#search'

  resources :users do
    member do
      post 'give_feedback'
    end
    resources :feedback
    resources :notifications
  end

  resources :tasks do
    resources :messages
    resources :reports
    resources :offers do
      post 'revoke'
      get  'accept'
    end
    member do
      post 'delete'
      post 'like'
      post 'unlike'
      post 'revoke'
      get 'complete'
      get 'chat'
    end
  end

  resources :comments

  root to: 'pages#index'

end

app/views/pages/_body_content.haml
.nav-bg
  = render partial: 'pages/nav'
= yield

app/views/pages/_footer.haml
%h1
  LOLOLOL

app/views/pages/_nav.haml
%nav.nav-bg
  .title
    = link_to 'Nicely', root_path, class: 'logo bold-links'
  %ul.nav-links
    - if user_signed_in?
      %li
        = link_to 'Logout', destroy_user_session_path, class: 'bold-links'
      %li
        %a{href: user_notifications_path(current_user), class: 'bold-links message-nav'}
          .icon
          %span.count
            = Notification.where(user_id: current_user.id, read_date: nil).count
      %li
        = link_to 'Me', user_path(current_user), class: 'bold-links'
      %li.underline
        = link_to 'New Task', new_task_path, class: 'bold-links'
    - else
      %li
        = link_to 'Login', new_user_session_path, class: 'bold-links'
    %li
      = link_to 'Search', search_path, class: 'bold-links'

app/views/pages/_notice.haml
.notice
  .message{class: flash[:notice][:type]}
    %h3
      = flash[:notice][:message]

app/views/pages/browse.haml
.browse
  .refine
    %ul
      %li
        %h3 Show:
      %li
        %h3
          = link_to 'Helpers', browse_path(tab: 'helpers'), class: generate_class('helpers')
      %li
        %h3
          = link_to 'Askers', browse_path(tab: 'askers'), class: generate_class('askers')
      %li
        %h3
          = link_to 'Tasks', browse_path(tab: 'tasks'), class: generate_class('tasks')
  .sort-by
    %ul
      %li
        %h1 Sort by:
      %li
        %h1
          = link_to 'Top', browse_path(tab: current_tab, sort: 'top'), class: generate_class('top')
      %li
        %h1
          = link_to 'Recent', browse_path(tab: current_tab, sort: 'recent'), class: generate_class('recent')
      %li
        %h1
          = link_to 'New', browse_path(tab: current_tab, sort: 'new'), class: generate_class('new-sort')
  .timespan
    %ul
      %li
        %h1 Timespan:
      %li
        %h1
          = link_to 'today', browse_path(tab: current_tab, sort: current_sort_order, time: 'today'), class: generate_class('today')
      %li
        %h1
          = link_to 'week', browse_path(tab: current_tab, sort: current_sort_order, time: 'week'), class: generate_class('week')
      %li
        %h1
          = link_to 'month', browse_path(tab: current_tab, sort: current_sort_order, time: 'month'), class: generate_class('month')
      %li
        %h1
          = link_to 'year', browse_path(tab: current_tab, sort: current_sort_order, time: 'year'), class: generate_class('year')

app/views/pages/feed.haml
.feed
  .refine
    %ul
      %li
        %h3 Show:
      %li
        %h3
          = link_to 'New', root_path(tab: 'new'), class: generate_class('new')
      %li
        %h3
          = link_to 'Nearby', root_path(tab: 'nearby'), class: generate_class('nearby')
      %li
        %h3
          = link_to 'Popular ', root_path(tab: 'popular'), class: generate_class('popular')
  .task-summaries
    = render partial: 'tasks/feed_summary', collection: @recent_tasks, locals: {gravatar_size: '80'}

  .pagination-container
    = will_paginate @recent_tasks

= content_for :javascript do
  = javascript_include_tag 'nicely/feed/manifest.js'
  :javascript
    jQuery(document).ready(function($){

      var feedView = new Nicely.Feed.FeedView(#{current_user.id}, {
        el: '.page'
      });

    });

app/views/pages/index.haml
.content
  .landing
    .text
      %h3 Making the world a better place, one favor at a time.
      %p
        = link_to 'Connect with Facebook', user_omniauth_authorize_path(:facebook), class: 'button'
  .recent-tasks
    = render partial: 'tasks/summary', collection: @recent_tasks, locals: { gravatar_size: '40'}

app/views/pages/search.haml
.feed
  .search-box
    = form_tag("/search", method: "get") do
      = label_tag(:q, "Search for:")
      = text_field_tag(:q, params[:q])
      = submit_tag("Search", class: 'button signup-button')

  .task-summaries
    - if @paginated_tasks
      = render partial: 'tasks/feed_summary', collection: @paginated_tasks, locals: {gravatar_size: '80'}

  .pagination-container
    -if @paginated_tasks
      = will_paginate @paginated_tasks

= content_for :javascript do
  = javascript_include_tag 'nicely/feed/manifest.js'
  :javascript
    jQuery(document).ready(function($){

      var feedView = new Nicely.Feed.FeedView(#{current_user.id}, {
        el: '.page'
      });

    });