config/routes.rb
Nicely::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match 'intro' => 'intro#onboard'
  match 'browse' => 'pages#browse'
  match 'search' => 'pages#search'

  resources :users do
    member do
      post 'give_feedback'
    end
    resources :feedback
    resources :notifications
  end

  resources :tasks do
    resources :messages
    resources :reports
    resources :offers do
      post 'revoke'
      get  'accept'
    end
    member do
      post 'delete'
      post 'like'
      post 'unlike'
      post 'revoke'
      get 'complete'
      get 'chat'
    end
  end

  resources :comments

  root to: 'pages#index'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :load_task
  before_filter :authenticate_user!, except: [:create]

  def create
    @offer = Offer.new
    @offer.user = User.find_by_id(params[:user_id])
    @task.offers << @offer
    # Send the task owner a notification that they received an offer
    offer_received = Notification.new(
        sender: @offer.user,
        user: @task.user,
        notification: t('notifications.offer_extended_html',
                        task_name: @task.title,
                        task_path: task_path(@task)),
        expiration_date: Time.now + 3.days,
        category: 'OFFER_RECEIVED'
    )
    if @offer.save && @task.save && offer_received.save
      render json: {offer: @offer, success: true }
    else
      render json: { success: false }
    end
  end

  def accept
    @task = Task.find_by_id(params[:task_id])
    redirect_to task_path(@task) and return unless current_user.id == @task.user.id
    @offer = Offer.find_by_id(params[:offer_id])
    assigned_to = Assignee.new
    assigned_to.user = @offer.user
    @task.assignee = assigned_to

    # Send the task offerer a notification that their offer was accepted
    offer_accepted = Notification.new(
        sender: @task.user,
        user: @offer.user,
        notification: t('notifications.task_assigned_html',
                        task_owner: @task.user.display_name,
                        task_owner_path: user_path(@task.user),
                        task_path: task_path(@task)),
        expiration_date: Time.now + 3.days,
        category: 'OFFER_ACCEPTED'
    )
    if assigned_to.save && @task.save && offer_accepted.save
      flash[:notice] = {type: "success", message: "Task assigned!"}
    else
      flash[:notice] = {type: "failure", message: "Task not assigned!"}
    end
    redirect_to task_path(@task) and return
  end

  def index
    render 'offers/index' and return
  end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_offer.haml
.offer
  .details
    .avatar
      = link_to image_tag(gravatar_url(offer.user.email, gravatar_size)), user_path(offer.user)
    .submission
      .submitter
        %span
          Submitted by
          = link_to offer.user.display_name, user_path(offer.user)
        %p.ago
          Offer created
          = distance_of_time_in_words_to_now(offer.created_at)
          ago
  - if current_user.id == offer.task.user.id && !offer.task.assignee
    .accept
      =  link_to 'Accept Offer', task_offer_accept_path(offer.task, offer), class: 'button-medium active'
  - if offer.task.assignee && offer.task.assignee.user.id == offer.user.id
    .accept
      Assigned

app/views/offers/index.haml
.facebook-notice
.offers
  .title
    %h3 Offers:
  - if !@task.offers.empty?
    = render partial: 'offers/offer', collection: @task.offers, locals: {gravatar_size: '80'}
  - else
    %h3 None so far